//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PacketType.proto
namespace packet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PacketHeader")]
  public partial class PacketHeader : global::ProtoBuf.IExtensible
  {
    public PacketHeader() {}
    
    private int _mSize;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mSize
    {
      get { return _mSize; }
      set { _mSize = value; }
    }
    private packet.PacketHeader.PacketType _mType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public packet.PacketHeader.PacketType mType
    {
      get { return _mType; }
      set { _mType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"PacketType")]
    public enum PacketType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_NONE", Value=0)]
      PKT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_CS_LOGIN", Value=1)]
      PKT_CS_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_SC_LOGIN", Value=2)]
      PKT_SC_LOGIN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PKT_SC_LOGIN_BROADCAST", Value=3)]
      PKT_SC_LOGIN_BROADCAST = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private packet.PacketHeader _mHeader;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mHeader", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public packet.PacketHeader mHeader
    {
      get { return _mHeader; }
      set { _mHeader = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResult")]
  public partial class LoginResult : global::ProtoBuf.IExtensible
  {
    public LoginResult() {}
    
    private packet.PacketHeader _mHeader;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mHeader", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public packet.PacketHeader mHeader
    {
      get { return _mHeader; }
      set { _mHeader = value; }
    }
    private int _mPlyaerID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mPlyaerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mPlyaerID
    {
      get { return _mPlyaerID; }
      set { _mPlyaerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginBroadcastResult")]
  public partial class LoginBroadcastResult : global::ProtoBuf.IExtensible
  {
    public LoginBroadcastResult() {}
    
    private packet.PacketHeader _mHeader;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mHeader", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public packet.PacketHeader mHeader
    {
      get { return _mHeader; }
      set { _mHeader = value; }
    }
    private int _mPlayerID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mPlayerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mPlayerID
    {
      get { return _mPlayerID; }
      set { _mPlayerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}