//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: packet_type.proto
namespace packet_type
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResult")]
  public partial class LoginResult : global::ProtoBuf.IExtensible
  {
    public LoginResult() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginBroadcastResult")]
  public partial class LoginBroadcastResult : global::ProtoBuf.IExtensible
  {
    public LoginBroadcastResult() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveKeyPressRequest")]
  public partial class MoveKeyPressRequest : global::ProtoBuf.IExtensible
  {
    public MoveKeyPressRequest() {}
    
    private bool _move_key_w_press;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"move_key_w_press", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool move_key_w_press
    {
      get { return _move_key_w_press; }
      set { _move_key_w_press = value; }
    }
    private bool _move_key_a_press;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"move_key_a_press", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool move_key_a_press
    {
      get { return _move_key_a_press; }
      set { _move_key_a_press = value; }
    }
    private bool _move_key_s_press;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"move_key_s_press", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool move_key_s_press
    {
      get { return _move_key_s_press; }
      set { _move_key_s_press = value; }
    }
    private bool _move_key_d_press;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"move_key_d_press", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool move_key_d_press
    {
      get { return _move_key_d_press; }
      set { _move_key_d_press = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttackKeyPressRequest")]
  public partial class AttackKeyPressRequest : global::ProtoBuf.IExtensible
  {
    public AttackKeyPressRequest() {}
    
    private bool _attack_key_mouse_left_press;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"attack_key_mouse_left_press", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool attack_key_mouse_left_press
    {
      get { return _attack_key_mouse_left_press; }
      set { _attack_key_mouse_left_press = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HPChangeResult")]
  public partial class HPChangeResult : global::ProtoBuf.IExtensible
  {
    public HPChangeResult() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private int _plyaer_hp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"plyaer_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plyaer_hp
    {
      get { return _plyaer_hp; }
      set { _plyaer_hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveResult")]
  public partial class MoveResult : global::ProtoBuf.IExtensible
  {
    public MoveResult() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private float _position_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_x
    {
      get { return _position_x; }
      set { _position_x = value; }
    }
    private float _position_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_y
    {
      get { return _position_y; }
      set { _position_y = value; }
    }
    private float _velocity_x;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"velocity_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float velocity_x
    {
      get { return _velocity_x; }
      set { _velocity_x = value; }
    }
    private float _velocity_y;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"velocity_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float velocity_y
    {
      get { return _velocity_y; }
      set { _velocity_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveStopResult")]
  public partial class MoveStopResult : global::ProtoBuf.IExtensible
  {
    public MoveStopResult() {}
    
    private int _plyaer_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"plyaer_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plyaer_id
    {
      get { return _plyaer_id; }
      set { _plyaer_id = value; }
    }
    private float _position_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_x
    {
      get { return _position_x; }
      set { _position_x = value; }
    }
    private float _position_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_y
    {
      get { return _position_y; }
      set { _position_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}