//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18449
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using packet_type;
using UnityEngine;
namespace Handler
{
	public class LoginResultHandler
	{
		GameManager game_manger = null;
		PrefabManager prefab_manager = null;

		public LoginResultHandler ()
		{
			prefab_manager = GameObject.Find ("Prefab Manager").GetComponent<PrefabManager> ();
		}

		public void Handle(LoginResult login_result)
		{
			prefab_manager.InstantiatePlayer (login_result.player_id);
			game_manger = GameObject.Find ("Game Manager").GetComponent<GameManager> ();
			game_manger.myObjectID = login_result.player_id;

			Debug.Log ("login_result");
			Debug.Log ( "player_id : " + login_result.player_id);
		}
	}
}

