//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

public class Player_Info
{
	public float x_;
	public float y_;
	public float velocity_x_;
	public float velocity_y_;
	public float acceleration_;
	public float angle_;
	
	public void Init(Transform dest_transform, float x, float y, float velocity_x, float velocity_y, float acceleration, float angle)
	{
		SetPosition (x, y, dest_transform);
		SetVelocity (velocity_x, velocity_y);
		SetAcceleration (acceleration);
		SetAngle (angle, dest_transform);
	}
	
	public void SetPosition (float x, float y, Transform dest_transform)
	{
		x_ = x;
		y_ = y;
		dest_transform.position = new Vector3(x_, y_);
	}
	public void SetVelocity(float velocity_x, float velocity_y)
	{
		velocity_x_ = velocity_x;
		velocity_y_ = velocity_y;
	}
	public void SetVelocity_x(float velocity_x)
	{
		velocity_x_ = velocity_x;
	}
	public void SetVelocity_y(float velocity_y)
	{
		velocity_y_ = velocity_y;
	}
	public void SetAcceleration(float acceleration)
	{
		acceleration_ = acceleration;
	}
	public void SetAngle(float angle, Transform dest_transform)
	{
		angle_ = angle;
		dest_transform.rotation = Quaternion.AngleAxis (angle_, Vector3.right);
	}
	
	public float GetAngle()
	{
		return angle_;
	}
}

